name: Ezerlist
options:
  bundleIdPrefix: com.ezerlist
  deploymentTarget:
    iOS: 17.0

targets:
  EzerlistShared:
    type: framework
    platform: iOS
    sources:
      - path: EzerlistShared/Sources
      - path: EzerlistShared/Resources
        excludes:
          - "*.xcdatamodeld/*.xcdatamodel"
    resources:
      - path: EzerlistShared/Resources
        includes:
          - "*.xcdatamodeld"
          - "*.xcdatamodeld/*.xcdatamodel"
    settings:
      base:
        INFOPLIST_FILE: EzerlistShared/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ezerlist.shared
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: EzerlistShared/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
    
  Ezerlist:
    type: application
    platform: iOS
    sources:
      - path: EzerlistApp
    dependencies:
      - target: EzerlistShared
    settings:
      base:
        INFOPLIST_FILE: EzerlistApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ezerlist.app
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: EzerlistApp/Info.plist
      properties:
        CFBundleName: Ezerlist
        CFBundleDisplayName: Ezerlist
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        LSRequiresIPhoneOS: true

  EzerlistWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: EzerlistWidget
    dependencies:
      - target: Ezerlist
      - target: EzerlistShared
    settings:
      base:
        INFOPLIST_FILE: EzerlistWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ezerlist.app.widget
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: EzerlistWidget/Info.plist
      properties:
        CFBundleName: EzerlistWidget
        CFBundleDisplayName: Ezerlist
        CFBundlePackageType: XPC!
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
